/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.org.locationtech.jts.jts.core)
    implementation("com.miglayout:miglayout-swing:5.3")
}

group = "com.beder"
version = "0.0.1-SNAPSHOT"
description = "Textures"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

application {
  mainClass.set("com.beder.texture.TextureGenius")
}

tasks.named<JavaExec>("run") {
  classpath += files("$projectDir/bin")
}